CREATE TABLE IF NOT EXISTS Collection (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS Flashcard (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CollectionId INTEGER NOT NULL,
    Question STRING NOT NULL,
    Answer STRING NOT NULL,
    SuccessfulAttempts INTEGER NOT NULL DEFAULT 0,
    FailedAttempts INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY(CollectionId) REFERENCES Collection(Id)
);
